name: mybudiluhur
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ^3.8.1

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    firebase_core: ^3.14.0
    flutter_bloc: ^9.1.1
    flutter_secure_storage: ^9.2.4
    http: ^1.4.0
    equatable: ^2.0.7
    bloc: ^9.0.0
    smooth_page_indicator: ^1.2.1
    hydrated_bloc: ^10.0.0
    path_provider: ^2.1.5
    font_awesome_flutter: ^10.8.0
    qr_flutter: ^4.1.0
    cached_network_image: ^3.4.1
    intl: ^0.20.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0
    bloc_test: ^10.0.0
    mocktail: ^1.0.4

flutter:
    uses-material-design: true
    assets:
        - assets/image/
    fonts:
        - family: Sniglet
          fonts:
              - asset: assets/fonts/Sniglet-Regular.ttf
        - family: SnigletBold
          fonts:
              - asset: assets/fonts/Sniglet-Regular.ttf
              - asset: assets/fonts/Sniglet-ExtraBold.ttf
                weight: 700
