// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRVohnYbhRmIGb84fe4nDevGDv50fRi6U',
    appId: '1:538997606381:web:7b889cde64db92574609e4',
    messagingSenderId: '538997606381',
    projectId: 'mybudiluhur-prod',
    authDomain: 'mybudiluhur-prod.firebaseapp.com',
    storageBucket: 'mybudiluhur-prod.firebasestorage.app',
    measurementId: 'G-8B70PXMR7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ2o8fOia9FjS400HkX5zdT54owUIZHFY',
    appId: '1:538997606381:android:2891e59651c686994609e4',
    messagingSenderId: '538997606381',
    projectId: 'mybudiluhur-prod',
    storageBucket: 'mybudiluhur-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZjNgzadGWCUgGrPitnfWKSo9Ln_7Xvy0',
    appId: '1:538997606381:ios:ad4088856e21e6104609e4',
    messagingSenderId: '538997606381',
    projectId: 'mybudiluhur-prod',
    storageBucket: 'mybudiluhur-prod.firebasestorage.app',
    iosBundleId: 'com.example.mybudiluhur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZjNgzadGWCUgGrPitnfWKSo9Ln_7Xvy0',
    appId: '1:538997606381:ios:ad4088856e21e6104609e4',
    messagingSenderId: '538997606381',
    projectId: 'mybudiluhur-prod',
    storageBucket: 'mybudiluhur-prod.firebasestorage.app',
    iosBundleId: 'com.example.mybudiluhur',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRVohnYbhRmIGb84fe4nDevGDv50fRi6U',
    appId: '1:538997606381:web:a16f02805c73ebf44609e4',
    messagingSenderId: '538997606381',
    projectId: 'mybudiluhur-prod',
    authDomain: 'mybudiluhur-prod.firebaseapp.com',
    storageBucket: 'mybudiluhur-prod.firebasestorage.app',
    measurementId: 'G-3W8RG0981P',
  );
}
